export const TABLE_RESIZE = 'TABLE_RESIZE'
export const CHANGE_TEXT = 'CHANGE_TEXT'
export const APPLY_STYLES = 'APPLY_STYLES'
export const CHANGE_STYLE = 'CHANGE_STYLE'
export const HEADER_TITTLE = 'HEADER_TITTLE'
export const DATE = 'DATE'
